### ISSUE TITLE
官网找不到9.0和9.1的安装包了

### ISSUE THREAD

**Issue by tangwan** [paynexss/ja-netfilter-studio3t-plugin#1]
刚下载的2023.9.2，按照文档配置后，激活码随便输提示错误。

<img width="322" alt="image" src="https://github.com/paynexss/ja-netfilter-studio3t-plugin/assets/15011585/c9fbd529-21c6-4828-bdb3-10f6d91ee5db">
<img width="777" alt="image" src="https://github.com/paynexss/ja-netfilter-studio3t-plugin/assets/15011585/7b59652b-a462-4126-8fa9-8d519be5ac5f">

**Comment by paynexss** [comment]
已更新9.2
